export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const SEND_MESSAGE_START = "SEND_MESSAGE_START";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILED  = "SEND_MESSAGE_FAILED";
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET";

export const FETCH_MESSAGES_START = "FETCH_MESSAGES_START";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILED = "FETCH_MESSAGES_FAILED";

export const DELETE_MESSAGE_START = "DELETE_MESSAGE_START";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILED = "DELETE_MESSAGE_FAILED";

export const UPLOAD_IMAGE_START = "UPLOAD_IMAGE_START";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED";
export const UPLOAD_IMAGE_IN_PROGRESS = "UPLOAD_IMAGE_IN_PROGRESS";
export const UPLOAD_IMAGE_CANCELED = "UPLOAD_IMAGE_CANCELED";
export const UPLOAD_IMAGE_URL_AFTER_SUCCESS = "UPLOAD_IMAGE_URL_AFTER_SUCCESS"; 

export const FETCH_IMAGES_START = "FETCH_IMAGES_START";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAILED = "FETCH_IMAGES_FAILED";

export const DELETE_IMAGE_START = "DELETE_IMAGE_START";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAILED = "DELETE_IMAGE_FAILED";